import './components/header-cristina/Header.js'
import './components/header-cristina/header-menu.js'
import './components/favorites-george/Favorites.js'
import './components/OrderNow/OrderNow.js'
import './components/go_up-catalin/go_up-catalin.js'
import './components/recipe_modal-alina/modal_recipe.js'
import './components/footer-cristina/footer_modal-cristina.js'